# 3.4.2020

# This script will look at known associations between mtDNA-CN and covariates

# load mtDNA-CN file
```{r}
load('/Volumes/JHPCE/dcs01/active/projects/GTeX/syang/look.version8/R_objects/final.mito.rds')
```


# Adjust for everything BUT age, sex, and Neutrophils
```{r}
library(splines)

final.mito$noAGE <- scale(resid(lm(mtDNA ~ Neutrophils + HSC + Megakaryocytes + COHORT + TRISCHD + SEX, data = final.mito)))
final.mito$noSEX <- scale(resid(lm(mtDNA ~ Neutrophils + HSC + Megakaryocytes + COHORT + TRISCHD + ns(AGE,2), data = final.mito)))
final.mito$noNEUT <- scale(resid(lm(mtDNA ~ HSC + Megakaryocytes + COHORT + TRISCHD + ns(AGE,2) + SEX, data = final.mito)))
```


# get associations for each:
```{r}
lm(noAGE ~ ns((AGE),2), data = final.mito) %>% summary
lm(noAGE ~ ns(scale(AGE),2), data = final.mito) %>% summary
library(ggplot2)
ggplot(final.mito, aes(AGE, noAGE)) + geom_point()

lm(noAGE ~ scale(AGE), data = final.mito) %>% summary
lm(noSEX ~ SEX, data = final.mito) %>% summary
# lm(mtDNA ~ SEX, data = final.mito) %>% summary
# lm(mtDNA ~ AGE, data = final.mito) %>% summary
pairs(~AGE + SEX + Neutrophils + HSC + Megakaryocytes, data = final.mito, lower.panel=twolines, diag.panel=mydiag.panel, upper.panel=panel.cor, label.pos=0.5, main="Correlation matrix of PCs and covariates", labels = c('age', 'sex', 'neutrophils', 'hsc', 'megakaryocytes'))

lm(noAGE ~ scale(AGE), data = final.mito) %>% summary
lm(noSEX ~ SEX, data = final.mito) %>% summary
lm(noNEUT ~ scale(Neutrophils), data = final.mito) %>% summary
```

# make a table:
```{r}
covs = c('Age', 'Sex (Female)', 'Neutrophils')
gtex = c(-0.06, 0.15, -0.19)
gtexse = c(0.05, 0.10, 0.05)
gtexp = c(0.18, 0.14, 8.4e-5)

aric = c(-0.02, 0.46, -0.14)
aricp = c(0.004, 9.95e-14,9.97e-16)
aricse = c(0.005, 0.06, 0.02)
power = c('28.68%', '79.44%', '97.48%')

show = data.frame(Covariate = covs, gtex = gtex, gtexse = gtexse, gtexp= gtexp, aric = aric, aricse = aricse, aricp= aricp, power = power)

library(htmlTable)
htmlTable(show[,-1], rnames = show[,1], cgroup = c('GTEx', 'ARIC', ''), n.cgroup = c(3, 3, 1), header = c('Effect estimate', 'Standard error', 'P-value', 'Effect estimate', 'Standard error', 'P-value', 'Power'))
```
