# 6.1.2020
# Updated 11.11.2020

# Make a table of UKB results for manuscript
```{r setup}
library(data.table)
library(knitr)
library(meta)
library(htmlTable)
library(yangR)
wdir <- paste0('/Volumes/JHPCE/dcs01/active/projects/GTeX/syang/look.version8/')
setwd(wdir)
opts_knit$set(root.dir = wdir)
```

# load results files
```{r}
load('/Volumes/JHPCE/dcs01/active/projects/GTeX/syang/look.version8/R_objects/UKB/show_inc.rds')
load('/Volumes/JHPCE/dcs01/active/projects/GTeX/syang/look.version8/R_objects/UKB/show_prev.rds')
```

# format for an htmlTable
```{r}
show_inc = as.data.frame(show_inc)
show_prev = as.data.frame(show_prev)

# Dan says use two sig digits!!!
formatbeta <- function (beta) 
{
    formatC(round(beta, 3), 2, format = "f")
}

show_inc$Lower = formatbeta(as.numeric(as.character(show_inc$Lower)))
show_inc$Upper = formatbeta(as.numeric(as.character(show_inc$Upper)))
show_inc$`Hazard ratio` = formatbeta(as.numeric(as.character(show_inc$`Hazard ratio`)))
show_inc$`P-value` = formatpval(as.numeric(as.character(show_inc$`P-value`)))
show_inc$CI = paste0(show_inc$Lower, ';', show_inc$Upper)

show_prev$Lower = formatbeta(as.numeric(as.character(show_prev$Lower)))
show_prev$Upper = formatbeta(as.numeric(as.character(show_prev$Upper)))
show_prev$`Hazard ratio` = formatbeta(as.numeric(as.character(show_prev$`Hazard ratio`)))
show_prev$`P-value` = formatpval(as.numeric(as.character(show_prev$`P-value`)))
show_prev$CI = paste0(show_prev$Lower, ';', show_prev$Upper)

htmlTable(show_inc[,c(1, 2, 7, 5, 6)], rnames = rep("", nrow(show_inc)), header =  c('Disease', '&nbsp;Hazard ratio&nbsp;', '&nbsp;Confidence interval&nbsp;', '&nbsp;Number of cases&nbsp;', '&nbsp;P-value&nbsp;'))

htmlTable(rbind(show_prev[,c(1, 2, 7, 5, 6)], show_inc[,c(1, 2, 7, 5, 6)]), rnames = rep("", 8), header =  c('Disease', '&nbsp;Hazard ratio&nbsp;', '&nbsp;Confidence interval&nbsp;', '&nbsp;Number of cases&nbsp;', '&nbsp;P-value&nbsp;'))
```

# For reviewers:
```{r}
load('/Volumes/JHPCE/dcs01/active/projects/GTeX/syang/look.version8/R_objects/UKB/show_inc_all.rds')


formatbeta <- function (beta) 
{
  formatC(round(beta, 3), 2, format = "f")
}

show_inc_all$Lower = formatbeta(as.numeric(as.character(show_inc_all$Lower)))
show_inc_all$Upper = formatbeta(as.numeric(as.character(show_inc_all$Upper)))
show_inc_all$`Hazard ratio` = formatbeta(as.numeric(as.character(show_inc_all$`Hazard ratio`)))
show_inc_all$`P-value` = formatpval(as.numeric(as.character(show_inc_all$`P-value`)))
show_inc_all$CI = paste0(show_inc_all$Lower, ';', show_inc_all$Upper)

show_inc_all$Method = rep(c('Array', 'Whole Exome Sequence'), 4)

array = subset(show_inc_all, Method == 'Array')
wes = subset(show_inc_all, Method == 'Whole Exome Sequence')

both = merge(array, wes, by = 'Disease', suffixes = c('_array', '_wes'))
show = both[,c(1, 2, 7, 6, 9, 14, 13, 12)]


htmlTable(show[c(4, 1, 2, 3),-1], rnames = show$Disease, cgroup = c('Array metric', 'Whole exome sequence metric', ''), n.cgroup = c(3,3,1), header = c('Hazard ratio', 'Confidence interval', 'P-value', 'Hazard ratio', 'Confidence interval', 'P-value', 'Cases/controls'))
```