# 4.12.2020

# This script will look at p-value QQ-plots from permutation testing!
```{r setup}
library(data.table)
library(knitr)
wdir <- paste0('/Volumes/JHPCE/dcs01/active/projects/GTeX/syang/look.version8/Whole Blood/with.gene.rds')
setwd(wdir)
opts_knit$set(root.dir = wdir)
```
		
# Annotate gene types
```{r}
load('/Volumes/JHPCE/dcs01/resources/ensembl/only.care.rds') # made in /dcs01/arking/arkinglab/resources/ensembl/try.read.R

w.annot <- merge(only.care, with.gene, by = 'gene_id') # 23758 yay
```

# qq-plot
```{r}
ordered <- w.annot[order(w.annot$pval),]
ordered$gene_type %>% as.factor %>% levels
ordered$pseudogenes <- 'No'
ordered$pseudogenes[grep('pseudogene', ordered$gene_type)] <- 'Yes'

title <- 'P-value QQ-plot for Blood by gene type'
pvals <- ordered$pval
pvals <- pvals
observed <- sort(pvals)
observed2 <- c(length(pvals))
observed2null <- -(log10(observed2/(length(observed2) + 1)))
pvals <- c(pvals, observed2null)
observed <- sort(pvals)
lobs <- -(log10(observed))
expected <- c(1:length(observed))
lexp <- -(log10(expected/(length(expected) + 1)))
m <- title
plot(c(0, 20), c(0, 20), col = "red", lwd = 4, type = "l",
     xlab = "Expected (-logP)", ylab = "Observed (-logP)",
     xlim = c(0, 7), ylim = c(0, 12), las = 1, xaxs = "i",
     yaxs = "i", bty = "l", main = m)
points(lexp, lobs, pch = 23, cex = 0.5, col = "black", bg = "black")

protein.coding<-subset(ordered, gene_type == ' protein_coding')

# get a lambda for protein coding:
chisq <- protein.coding$t_value^2
chisq <- qchisq(1-(protein.coding$pval),1)

# (2) Calculate lambda gc (λgc) # how does your median chisq value compare?
median(chisq)/qchisq(0.5,1)



nom.sig <- subset(protein.coding, pval < 0.05)

pvals<-protein.coding$pval
observed <- sort(pvals)
pc<-length(observed)
pc<-paste("Protein-coding [",pc,"]",sep="")
lobs <- -(log10(observed))
expected <- c(1:length(observed))
lexp <- -(log10(expected / (length(expected)+1)))
points(lexp, lobs, pch=23, cex=.5, col="brown", bg="brown")

#############################################
######### plot pseudogenes ##################
#############################################

pseudo <-subset(ordered, pseudogenes == 'Yes')

pvals<-pseudo$pval
observed <- sort(pvals)
ps<-length(observed)
ps<-paste("Pseudogenes [",ps,"]",sep="")
lobs <- -(log10(observed))
expected <- c(1:length(observed))
lexp <- -(log10(expected / (length(expected)+1)))
points(lexp, lobs, pch=23, cex=.5, col="blue", bg="blue")

##########################################
######### plot lincRNAs ##################
##########################################

linc <-subset(ordered, gene_type == ' lincRNA')

pvals<-linc$pval
observed <- sort(pvals)
lc<-length(observed)
lc<-paste("lincRNAs [",lc,"]",sep="")
lobs <- -(log10(observed))
expected <- c(1:length(observed))
lexp <- -(log10(expected / (length(expected)+1)))
points(lexp, lobs, pch=23, cex=.5, col="orange", bg="orange")

###########################################
######### plot antisense ##################
###########################################

anti <-subset(ordered, gene_type == ' antisense')

pvals<-anti$pval
observed <- sort(pvals)
a<-length(observed)
a<-paste("Antisense [",a,"]",sep="")
lobs <- -(log10(observed))
expected <- c(1:length(observed))
lexp <- -(log10(expected / (length(expected)+1)))
points(lexp, lobs, pch=23, cex=.5, col="green", bg="green")

###################################
######### legend ##################
###################################

legend("bottomright", c("Expected","Observed",pc,ps,lc,a), cex=0.8, col=c("red","black","brown","blue","orange","green"), pch=18)
```