# 3.4.2020

# This script will look at known associations between mtDNA-CN and covariates

# load mtDNA-CN file
```{r}
load('/Volumes/JHPCE/dcs01/active/projects/GTeX/syang/look.version8/R_objects/final.mito.rds')
```

# Check BMI super quickly
```{r}
library(magrittr)
lm(mtDNA ~ BMI, data = final.mito) %>% summary
```

# Adjust for everything BUT age, sex, and Neutrophils
```{r}
library(splines)

final.mito$noAGE <- scale(resid(lm(mtDNA ~ Neutrophils + HSC + Megakaryocytes + COHORT + TRISCHD + SEX, data = final.mito)))
final.mito$noSEX <- scale(resid(lm(mtDNA ~ Neutrophils + HSC + Megakaryocytes + COHORT + TRISCHD + ns(AGE,2), data = final.mito)))
final.mito$noNEUT <- scale(resid(lm(mtDNA ~ HSC + Megakaryocytes + COHORT + TRISCHD + ns(AGE,2) + SEX, data = final.mito)))
```

# plot for age:
```{r}
# get p-values:
lm(noAGE ~ AGE, data = final.mito) %>% summary %>% coef
lm(noSEX ~ SEX, data = final.mito) %>% summary %>% coef

age = ggplot(final.mito, aes(AGE, noAGE)) + geom_point() + geom_smooth(method = 'lm') + theme_classic() + xlab('Age at blood draw') + ylab('Adjusted mtDNA-CN')
sex = ggplot(final.mito, aes(SEX, noSEX)) + geom_boxplot() + theme_classic() + xlab('Biological sex') + ylab('Adjusted mtDNA-CN') + scale_x_discrete(labels = c('Male','Female'))

library(patchwork)
age + sex
```

# get associations for each:
```{r}
lm(noAGE ~ ns((AGE),2), data = final.mito) %>% summary
lm(noAGE ~ ns(scale(AGE),2), data = final.mito) %>% summary
library(ggplot2)
ggplot(final.mito, aes(AGE, noAGE)) + geom_point()

lm(noAGE ~ scale(AGE), data = final.mito) %>% summary
lm(noSEX ~ SEX, data = final.mito) %>% summary
# lm(mtDNA ~ SEX, data = final.mito) %>% summary
# lm(mtDNA ~ AGE, data = final.mito) %>% summary
pairs(~AGE + SEX + Neutrophils + HSC + Megakaryocytes, data = final.mito, lower.panel=twolines, diag.panel=mydiag.panel, upper.panel=panel.cor, label.pos=0.5, main="Correlation matrix of PCs and covariates", labels = c('age', 'sex', 'neutrophils', 'hsc', 'megakaryocytes'))

lm(noAGE ~ scale(AGE), data = final.mito) %>% summary
lm(noSEX ~ SEX, data = final.mito) %>% summary
lm(noNEUT ~ scale(Neutrophils), data = final.mito) %>% summary
```


# make a table:
```{r}
covs = c('Age', 'Sex (Female)', 'Neutrophils')
gtex = c(-0.06, 0.15, -0.19)
gtexse = c(0.005, 0.102, 0.005)
gtexp = c(0.18, 0.14, 8.4e-5)

aric = c(-0.02, 0.46, -0.14)
aricp = c(0.004, 9.95e-14,9.97e-16)
aricse = c(0.005, 0.06, 0.02)
power = c('28.68%', '79.44%', '97.48%')

show = data.frame(Covariate = covs, gtex = gtex, aric = aric, gtexp= gtexp, aricp = aricp, gtexse = gtexse, aricse = aricse, power = power)

library(htmlTable)
htmlTable(show, rnames = rep('', nrow(show)), header = c('Covariate', 'GTEx effect estimate', 'ARIC effect estimate', 'GTEx p-value', 'ARIC p-value', 'GTEx standard error', 'ARIC standard error', 'Power'))
```

# for a table:
```{r}
lm(noAGE ~ scale(AGE), data = final.mito) %>% summary %>% coef -> age
lm(noSEX ~ SEX, data = final.mito) %>% summary %>% coef -> sex
lm(noNEUT ~ scale(Neutrophils), data = final.mito) %>% summary %>% coef -> neut

show <- data.frame(Age = age[2,c(1,4)], Sex = sex[2,c(1,4)], Neutrophils = neut[2,c(1,4)])
show <- as.data.frame(t(show))
colnames(show) <- c('beta', 'pval')
important <- show
important$beta <- formatC(important$beta, format = "e", digits = 2)
important$pval <- formatC(important$pval, format = "e", digits = 2)

kable_styling(kable(important), full_width = F)
```